import type { Topic } from "./types";

/**
 * Discovery topics (2026-10-08). A topic is a user INTENT, not a
 * classification of the amal itself — an amal only appears under a
 * topic per its TopicLinkEntry, and "dua-for" links require cited
 * evidence that the amal's own words ask for it (content tests enforce
 * this). Topics rendered in the UI only when at least one public amal
 * links to them.
 *
 * searchTerms carry the Bangla/English/Banglish variants a user might
 * type; these feed the topic side of the search index in search.ts.
 */
export const TOPICS: Topic[] = [
  {
    id: "forgiveness",
    name: { en: "Forgiveness", bn: "ক্ষমা" },
    description: {
      en: "Seeking Allah's pardon for sins.",
      bn: "গুনাহের জন্য আল্লাহর কাছে ক্ষমা চাওয়া।",
    },
    searchTerms: [
      "ক্ষমা",
      "মাফ",
      "গুনাহ",
      "গোনাহ",
      "পাপ",
      "choma",
      "khoma",
      "kshoma",
      "gonah",
      "pap",
      "forgiveness",
      "pardon",
      "maghfirah",
      "magfirat",
      "tawbah",
      "tauba",
      "তওবা",
    ],
  },
  {
    id: "istighfar",
    name: { en: "Istighfar", bn: "ইস্তিগফার" },
    description: {
      en: "The practice of seeking forgiveness itself.",
      bn: "ক্ষমা চাওয়ার আমল নিজেই।",
    },
    searchTerms: [
      "ইস্তিগফার",
      "আস্তাগফিরুল্লাহ",
      "ইস্তেগফার",
      "istighfar",
      "istegfar",
      "astaghfirullah",
      "istighfar practice",
    ],
  },
  {
    id: "salawat",
    name: { en: "Salawat", bn: "দরুদ" },
    description: {
      en: "Blessings upon the Prophet ﷺ.",
      bn: "রাসূলুল্লাহ (সা.)-এর ওপর দরুদ ও সালাম।",
    },
    searchTerms: [
      "দরুদ",
      "দরুদ শরীফ",
      "সালাওয়াত",
      "শুক্রবার",
      "durod",
      "dorud",
      "salawat",
      "salat on prophet",
      "darood",
    ],
  },
  {
    id: "gratitude",
    name: { en: "Gratitude", bn: "শুকরিয়া" },
    description: {
      en: "Thanking Allah for His blessings.",
      bn: "আল্লাহর নিয়ামতের শুকরিয়া আদায় করা।",
    },
    searchTerms: [
      "শুকরিয়া",
      "কৃতজ্ঞতা",
      "শোকর",
      "shukriya",
      "shokor",
      "kritoggota",
      "gratitude",
      "thanks",
      "hamd",
    ],
  },
  {
    id: "general-dhikr",
    name: { en: "Dhikr", bn: "জিকির" },
    description: {
      en: "General remembrance of Allah.",
      bn: "সাধারণ আল্লাহর জিকির।",
    },
    searchTerms: [
      "জিকির",
      "জিকর",
      "তাসবিহ",
      "স্মরণ",
      "dhikr",
      "zikir",
      "zikr",
      "tasbih",
      "remembrance",
    ],
  },
  {
    id: "sabr",
    name: { en: "Patience", bn: "ধৈর্য" },
    description: {
      en: "Steadfastness through hardship.",
      bn: "কষ্টের মধ্যে ধৈর্য ধরা।",
    },
    searchTerms: [
      "ধৈর্য",
      "সবর",
      "ধৈর্য্য",
      "সহনশীলতা",
      "sabor",
      "shobor",
      "dhairjo",
      "dhoirjo",
      "sabr",
      "patience",
      "perseverance",
    ],
  },
  {
    id: "tawakkul",
    name: { en: "Tawakkul", bn: "তাওয়াক্কুল" },
    description: {
      en: "Trusting and relying upon Allah.",
      bn: "আল্লাহর ওপর ভরসা ও নির্ভরতা।",
    },
    searchTerms: [
      "তাওয়াক্কুল",
      "ভরসা",
      "নির্ভর",
      "tawakkul",
      "towakkul",
      "trust in allah",
      "reliance",
    ],
  },
  {
    id: "anxiety-worry",
    name: { en: "Anxiety & worry", bn: "দুশ্চিন্তা" },
    description: {
      en: "Relief from worry and distress.",
      bn: "দুশ্চিন্তা ও উদ্বেগ থেকে মুক্তি।",
    },
    searchTerms: [
      "দুশ্চিন্তা",
      "উদ্বেগ",
      "দুঃখ",
      "মানসিক অস্থিরতা",
      "টেনশন",
      "duschinta",
      "dushchinta",
      "udbeg",
      "tension",
      "anxiety",
      "worry",
      "distress",
      "sadness",
    ],
  },
  {
    id: "sleep-evening",
    name: { en: "Sleep & evening", bn: "ঘুম ও সন্ধ্যা" },
    description: {
      en: "Night and bedtime remembrance.",
      bn: "রাত ও ঘুমানোর আগের জিকির।",
    },
    searchTerms: [
      "ঘুম",
      "ঘুমানোর আগে",
      "রাত",
      "সন্ধ্যা",
      "বিছানা",
      "ghum",
      "ghumar age",
      "rat",
      "shondha",
      "sleep",
      "night",
      "bedtime",
      "evening",
    ],
  },
  {
    id: "protection",
    name: { en: "Protection", bn: "হেফাজত" },
    description: {
      en: "Seeking Allah's guarding care.",
      bn: "আল্লাহর কাছে হেফাজত চাওয়া।",
    },
    searchTerms: [
      "হেফাজত",
      "সুরক্ষা",
      "আশ্রয়",
      "অক্ষত রাখা",
      "hefajot",
      "hefazot",
      "shurokkha",
      "protection",
      "safety",
      "refuge",
    ],
  },
  {
    id: "rizq",
    name: { en: "Rizq", bn: "রিজিক" },
    description: {
      en: "Provision and sustenance from Allah.",
      bn: "আল্লাহর কাছে রিজিক ও জীবিকা চাওয়া।",
    },
    searchTerms: [
      "রিজিক",
      "রুজি",
      "জীবিকা",
      "রিজিক বৃদ্ধি",
      "আয়",
      "রিজ",
      "rijik",
      "rizik",
      "ruji",
      "jibika",
      "rizq",
      "sustenance",
      "provision",
      "income",
      "livelihood",
    ],
  },
  {
    id: "guidance",
    name: { en: "Guidance", bn: "হেদায়েত" },
    description: {
      en: "Seeking Allah's guidance and taqwa.",
      bn: "আল্লাহর কাছে হেদায়েত ও তাকওয়া চাওয়া।",
    },
    searchTerms: [
      "হেদায়েত",
      "হেদায়াত",
      "পথ দেখানো",
      "তাকওয়া",
      "hedayet",
      "hedayat",
      "taqwa",
      "guidance",
      "right path",
      "siratul mustaqim",
    ],
  },
  {
    id: "akhirah",
    name: { en: "Akhirah", bn: "আখিরাত" },
    description: {
      en: "Good of the Hereafter and Jannah.",
      bn: "আখিরাতের কল্যাণ ও জান্নাত কামনা।",
    },
    searchTerms: [
      "আখিরাত",
      "পরকাল",
      "জান্নাত",
      "দোজখ থেকে বাঁচা",
      "akhirat",
      "porkal",
      "jannat",
      "hereafter",
      "paradise",
      "hellfire protection",
    ],
  },
  {
    id: "family-parents",
    name: { en: "Family & parents", bn: "পরিবার ও বাবা-মা" },
    description: {
      en: "Duas for parents and family.",
      bn: "বাবা-মা ও পরিবারের জন্য দোয়া।",
    },
    searchTerms: [
      "বাবা",
      "মা",
      "বাবা-মার জন্য দোয়া",
      "পরিবার",
      "সন্তান",
      "baba",
      "ma",
      "babar mar jonno dua",
      "poribar",
      "shontan",
      "parents",
      "family",
      "mother",
      "father",
    ],
  },
];
